version: '3.9'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    # hostname: app.example.com
    # depends_on:
    #   - dependency
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    # networks:
    #   - network-name

networks:
  network-name:
